
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: kafka
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: gitlab-registry.cern.ch/db/spark-service/spark-k8s-examples:v1.1-060519
  # if to pull new image if time: imagePullPolicy: Always
  sparkVersion: 2.4.1
  mainClass: ch.cern.monitoring.KafkaRead
  mainApplicationFile: local:///usr/hdp/spark/examples/jars/spark-k8s-examples-assembly-1.1.jar
  mode: cluster
  arguments:
    - "fts_raw_complete"
    - "monit-kafkax-dev-b3b87d619c.cern.ch:9092"
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "1024m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    instances: 2
    cores: 1
    memory: "2048m"
    labels:
      version: 2.4.0
  restartPolicy:
    type: Always