#
# Copyright 2018 CERN/Switzerland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: tpcds-data-gen
  namespace: default
spec:
  type: Scala
  mode: cluster
  # Use staging (tpcds image)
  image: gitlab-registry.cern.ch/db/spark-service/docker-registry/spark-on-k8s-staging:v2.4.0
  imagePullPolicy: Always
  mainClass: ch.cern.tpcds.DataGenTPCDS
  mainApplicationFile: <path-to>/spark-service-examples/target/scala-2.11/spark-service-examples_2.11-0.2.0.jar
  arguments:
    # working directory (existing or not)
    - "s3a://<your-cluster-bucket>/TPCDS-TEST"
    # Path to kit in the docker image
    - "/opt/tpcds-kit/tools"
    # Scale factor (in GB)
    - "1"
    # Generate data num partitions
    - "100"
    # Create the partitioned fact tables
    - "false"
    # Shuffle to get partitions coalesced into single files.
    - "false"
    # Logging set to WARN
    - "true"
  deps:
    jars:
      - <path-to>/spark-service/spark-service-examples/libs/scala-logging_2.11-3.9.0.jar
      - <path-to>/spark-service/spark-service-examples/libs/spark-sql-perf_2.11-0.5.0-SNAPSHOT.jar
  sparkConf:
    "spark.network.timeout": "1200"
    "fs.s3a.connection.timeout": "1200000"
    "fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.maximum": "200"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    "spark.hadoop.fs.s3a.multipart.size": "10485760"
    "spark.hadoop.fs.s3a.multipart.threshold": "104857600"
    "spark.storage.blockManagerTimeoutIntervalMs": "300000"
    "spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version": "2"
    "spark.hadoop.mapreduce.fileoutputcommitter.cleanup-failures.ignored": "true"
  driver:
    cores: 4
    coreLimit: "4096m"
    memory: "6000m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    instances: 50
    cores: 2
    memory: "6000m"
    labels:
      version: 2.4.0
  restartPolicy: Never
