# Support for Python is experimental, and requires building SNAPSHOT image of Apache Spark,
# with `imagePullPolicy` set to Always
#
# Example:
# export AWS_ACCESS_KEY_ID=<redacted>
# export AWS_SECRET_ACCESS_KEY=<redacted>
# ./sparkctl create ./jobs/pyspark-deps.yaml -u s3a://{{ bucket-name }} -e "https://s3.cern.ch" --public --override

apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: py-wordcount
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: gitlab-registry.cern.ch/db/spark-service/docker-registry/spark:v2.4.0-hadoop3.1
  imagePullPolicy: Always
  mainApplicationFile: {{ path-to-examples }}/src/main/python/wordcount-with-deps.py
  deps:
    pyfiles:
       - {{ path-to-examples }}/libs/wordcount_python_job.zip
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "2000m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "2000m"
    labels:
      version: 2.4.0
  restartPolicy: Never