# Example:
# create registry deploy token https://gitlab.cern.ch/help/user/project/deploy_tokens/index.md
# kubectl create secret docker-registry {{ yoursecret }} --docker-server=https://gitlab-registry.cern.ch --docker_username={{ deploy_token_name }} --docker_password={{ deploy_token_password }}
# ./sparkctl create ./jobs/spark-pi.yaml

apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: {{ private imgage }}
  imagePullPolicy: Always
  imagePullSecret:
    - {{ yoursecret }}
  mainClass: ch.cern.sparkrootapplications.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-service-examples_2.11-0.3.0.jar
  mode: cluster
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "1024m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    instances: 1
    cores: 1
    memory: "1024m"
    labels:
      version: 2.4.0
  restartPolicy: Never
