# Support for Python is experimental, and requires building SNAPSHOT image of Apache Spark,
# with `imagePullPolicy` set to Always
#
# Example:
# ./sparkctl create ./jobs/spark-pyfiles.yaml

apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: pyfiles
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: gitlab-registry.cern.ch/db/spark-service/spark-k8s-examples:v2.4.0-hadoop3.1-examples
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pyfiles.py
  arguments:
    - python2.7
  deps:
    pyfiles:
      - local:///opt/spark/examples/src/main/python/py_container_checks.py
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
  restartPolicy: Never