apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: ScheduledSparkApplication
metadata:
  name: spark-pi-schedule
  namespace: default
spec:
  schedule: "@every 5m"
  concurrencyPolicy: Allow
  template:
    type: Scala
    mode: cluster
    image: gitlab-registry.cern.ch/db/spark-service/docker-registry/spark:v2.4.0-hadoop3.1-examples
    imagePullPolicy: IfNotPresent
    mainClass: ch.cern.sparkrootapplications.examples.SparkPi
    mainApplicationFile: local:///opt/spark/examples/jars/spark-service-examples_2.11-0.3.0.jar
    mode: cluster
    driver:
      cores: 0.1
      coreLimit: "200m"
      memory: "512m"
      labels:
        version: 2.4.0
      serviceAccount: spark
    executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        version: 2.4.0
    restartPolicy: Never
